version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: DRF_user
      POSTGRES_PASSWORD: DRF_password
      POSTGRES_DB: DRF_database_name
    restart: always
    ports:
    - "5432:5432"

  backend:
    build: ../DRF_test/.
    command: gunicorn DRF_test.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
